name: Publish new package into test pypi

on: [push, pull_request]


jobs:
  build_archs:
    name: Build wheels manylinux_aarch64
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_ARCHS_LINUX: aarch64

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

